weight = 1

title = "Realcupy"

copyright = "&copy; 2024 All Rights Reserved."
	[params.author]
	name = "Hemlo! I'm Jhonas"
	image = "img/image.png"
	headline = "Sipping ☕ coffee right now."
	
	links = [
	  { github = "https://github.com/realcupy" , linkedin = "https://linkedin.com/in/jhonascabanero", email = "mailto:realcupy@proton.me", telegram = "https://t.me/realcupy" }
	]