languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Realcupy_"

copyright = "&copy; 2023 All Rights Reserved."
[author]
	name = "Hemlo! I'm Jhonas"
	image = "img/image.jpg"
	headline = "Sipping ☕ coffee right now."
	
	links = [
	  { github = "https://github.com/realcupy" , linkedin = "https://linkedin.com/in/jhonascabanero", telegram = "https://t.me/realcupy" }
	]
